version: '2'
services: 
  mysql:
    image: mysql:latest
    container_name: mysql-server-new
    command: --default-authentication-plugin=mysql_native_password
    volumes:
    - .:/application
    restart: always
    environment: 
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=my_db
    - MYSQL_USER=user
    - MYSQL_PASSWORD=pass
    ports: 
    - "8082:3306"
  
  website:
    container_name: php72
    build:
      context: ./Source
    volumes: 
    - ./Source/PHP:/var/www/html
    ports: 
    - "8000:80"
    depends_on: 
    - mysql