version: '2'
services:
        www01:
                build: .
                container_name: 001_www01_1
                ports:
                        - "80:80"
                volumes:
                        - ./src:/var/www/html/
                depends_on:
                        - mysql
              
        mysql:
                image: mysql:8.0
                container_name: test-mysql
                command: --default-authentication-plugin=mysql_native_password
                restart: always
                ports:
                    - 6603:3306
                environment:
                    - MYSQL_ROOT_PASSWORD=root
                    - MYSQL_DATABASE=db
                    - MYSQL_USER=harshada
                    - MYSQL_PASSWORD=pass
                volumes:
                        - .:/application
                        - ./script/demo.sql:/docker-entrypoint-initdb.d/dump.sql
               
